FitnessWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from workouts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('member/', views.member, name='member'),
    path('program/', views.program, name='program'),
    path('about/', views.about, name='about'),
    path('workout_form/', views.createWorkout, name='workout_form'),
    path('update_workout/<int:id>/', views.updateWorkout, name='update_workout'),
    path('', views.index, name='index'),
    path('bodybuilding/', views.BodyBuilding, name='bodybuilding'),
    path('aerobic/', views.Aerobic, name="aerobic"),
    path('exercise/<int:exercise_id>/', views.exercise_detail, name="exercise_detail"),
    path('tinymce/', include('tinymce.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:id>/', views.blog_detail, name="blog_detail"),
    path('<int:id>/delete/', views.comment_delete, name="comment_delete"),
]

workouts/models.py
from django.db import models
from tinymce import HTMLField
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models.fields import DateField
# Create your models here.
class Category(models.Model):
    TYPE = (
        ('Body Building','Body Building'),
        ('Aerobic', 'Aerobic'),
        ('Weight Lifting', 'Weight Lifting'),
        ('Yoga','Yoga'),
    )
    category = models.CharField(max_length=100, choices=TYPE)

    def __str__(self):
        return self.category

class Exercise(models.Model):
    image = models.ImageField(upload_to='images')
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    content = HTMLField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('exercise_detail', kwargs={
            'exercise_id':self.id
        })

class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(blank=True, null=True, upload_to='images')

    def __str__(self):
        return self.user.username


class Workout(models.Model):
    name = models.CharField(max_length=100)
    STATUS = (
        ('In progress', 'In progress'),
        ('Finished', 'Finished')
    )

    member = models.ForeignKey(Member, null=True, blank=True, on_delete=models.CASCADE)
    date_of_working = models.DateField()
    exercise = models.ManyToManyField(Exercise)
    status = models.CharField(max_length=50, null=True, blank=True, choices=STATUS)

    def __str__(self):
        return self.name

workouts/forms.py
from django import forms
from django.forms import ModelForm
from .models import Workout, Member

class DateInput(forms.DateInput):
    input_type = 'date'

class WorkoutForm(ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(WorkoutForm, self).__init__(*args, **kwargs)
        self.fields['member'].queryset = Member.objects.filter(user_id=user)

    class Meta:
        model = Workout
        fields = '__all__'
        widgets = {'date_of_working':DateInput()}

class MemberForm(ModelForm):
    class Meta:
        model = Member
        fields = ['profile_pic']

workouts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Exercise, Member, Workout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .forms import WorkoutForm, MemberForm
from blog.models import Blog

# Create your views here.
def index(request):
    recent_blogs = Blog.objects.order_by('-timestamp')[:3]
    context = {
        'recent_blogs':recent_blogs
    }
    return render(request, 'index.html', context)

def BodyBuilding(request):
    BodyBuildingExercise = Exercise.objects.filter(category__category="Body Building")
    context = {
        'BodyBuildingExercise':BodyBuildingExercise
    }
    return render(request, 'bodybuilding.html', context)

def Aerobic(request):
    AerobicExercise = Exercise.objects.filter(category__category="Aerobic")
    context = {
        'AerobicExercise':AerobicExercise
    }
    return render(request, 'aerobic.html', context)


def exercise_detail(request, exercise_id):
    exercise = get_object_or_404(Exercise, id=exercise_id)
    context = {
        'exercise':exercise
    }
    return render(request, 'exercise_detail.html', context)

def registerPage(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            Member.objects.create(user=user)
            return redirect('login')

    context = {
        'form':form
    }
    return render(request, 'register.html', context)

def loginPage(request):
    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('index')

    return render(request, 'login.html')


def logoutPage(request):
    logout(request)
    return redirect('login')


def member(request):
    member = Member.objects.get(user=request.user)
    workouts = member.workout_set.all()
    total_workouts = workouts.count()
    in_progres = workouts.filter(status="In progress").count()
    finished = workouts.filter(status="Finished").count()
    form = MemberForm(instance=member)
    if request.method == "POST":
        form = MemberForm(request.POST, request.FILES, instance=member)
        if form.is_valid():
            form.save()
    context = {
        'member':member,
        'workouts':workouts,
        'total_workouts':total_workouts,
        'in_progres':in_progres,
        'finished':finished,
        'form':form
    }
    return render(request, 'member.html', context)


def createWorkout(request):
    member = Member.objects.get(user=request.user)
    form = WorkoutForm(request.user)
    if request.method == "POST":
        form = WorkoutForm(request.user, request.POST)

        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('/')

    context = {
        'form':form
    }
    return render(request, 'workout_form.html', context)

def updateWorkout(request, id):
    workout = Workout.objects.get(id=id)
    form = WorkoutForm(request.user, instance=workout)

    if request.method == "POST":
        form = WorkoutForm(request.user, request.POST, instance=workout)

        if form.is_valid():
            form.instance.workout = workout
            form.save()
            return redirect('/')

    context = {
            'form':form
    }
    return render(request, 'workout_form.html', context)


def program(request):
    return render(request, 'program.html')

def about(request):
    return render(request, 'about.html')

templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="ftco-about d-md-flex bg-light">
  <div class="one-half img" style="background-image: url({% static 'images/about-2.jpg' %});">
    <a href="https://vimeo.com/45830194" class="icon popup-vimeo d-flex justify-content-center align-items-center">
      <span class="icon-play"></a>

  </div>
  <div class="one-half ftco-animate">
    <div class="heading-section ftco-animate ">
      <h3 class="subheading">About Muscle</h3>
      <h2 class="mb-5">Welcome <br>To Our Gym</h2>
    </div>
    <div>
      <p>On her way she met a copy. The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their.</p>
    </div>
  </div>
</section>

{% endblock content %}

templates/aerobic.html
{% extends 'base.html' %}

{% block content %}
{% if request.user.is_authenticated %}
<br><br><br>
<div class="row">
{% for exercise in AerobicExercise %}
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{ exercise.image.url }}" height="300px" width="250px" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{ exercise.name }}</h5>
    <a href="{{ exercise.get_absolute_url }}" class="btn btn-primary">See content</a>
  </div>
</div>
{% endfor %}
</div>
{% else %} <br> <br> <br>
You need to log in to see this page
{% endif %}
{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
  {% include 'head.html' %}
  </head>

  <body>
  {% include 'nav.html' %}
  {% block content %}
  {% endblock content %}

  {% include 'footer.html' %}
  {% include 'scripts.html' %}
  </body>

</html>

templates/blog_detail.html
{% extends 'base.html' %}


{% block content %}
<div class="col-md-4 d-flex ftco-animate">
  <div class="blog-entry justify-content-end">
    <img src="{{ blog.image.url }}" height="200px" width="200px" alt="">
    <div class="text p-4 float-right d-block">
      <div class="meta">
        <div><a href="#">{{ blog.timestamp }}</a></div>
        <div><a href="#" class="meta-chat"><span class="icon-chat"></span> {{ blog.comments.count }}</a></div>
      </div>
      <h3 class="heading mt-2"><a href="#">{{ blog.title }}</a></h3>
      <p>{{ blog.content }}</p>
    </div>
  </div>
</div> <br>

{% for comment in blog.get_comments %}
{% if request.user.is_staff %}
<a href="{% url 'blog:comment_delete' comment.id %}">Delete comment</a>
{% endif %}
<br>
{% if comment.user.member.profile_pic %}
<img src="{{ comment.user.member.profile_pic.url }}" width="70px" alt="">
{% endif %}

{{ comment.timestamp|timesince }} ago <br>
{{comment.user.username }} <br>
{{comment.content }} <br>


{% endfor %}

<br><br>
<h2>Leave a comment</h2><br>

{% if request.user.is_authenticated %}
<form method="POST" action="">
{% csrf_token %}
{{ form }}
<button type="submit">Leave a comment</button>
</form>
{% else %}
You need to log in to leave a comment
{% endif %}
{% endblock content %}

templates/bodybuilding.html
{% extends 'base.html' %}

{% block content %}
{% if request.user.is_authenticated %}
<br><br><br>
<div class="row">
{% for exercise in BodyBuildingExercise%}
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{ exercise.image.url }}" height="300px" width="250px" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">{{ exercise.name }}</h5>
    <a href="{{ exercise.get_absolute_url }}" class="btn btn-primary">See content</a>
  </div>
</div>
{% endfor %}
</div>
{% else %} <br> <br> <br>
You need to log in to see this page
{% endif %}
{% endblock content %}

templates/footer.html
{% load static %}
<footer class="ftco-footer ftco-section img">
  <div class="overlay"></div>
  <div class="container">
    <div class="row mb-5">
      <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">About Us</h2>
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
            <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
            <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
          </ul>
        </div>
      </div>

      <div class="col-lg-2 col-md-6 mb-5 mb-md-5">
         <div class="ftco-footer-widget mb-4 ml-md-4">
          <h2 class="ftco-heading-2">Services</h2>
          <ul class="list-unstyled">
            <li><a href="#" class="py-2 d-block">Boost Your Body</a></li>
            <li><a href="#" class="py-2 d-block">Achieve Your Goal</a></li>
            <li><a href="#" class="py-2 d-block">Analyze Your Goal</a></li>
            <li><a href="#" class="py-2 d-block">Improve Your Performance</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 mb-5 mb-md-5">
        <div class="ftco-footer-widget mb-4">
          <h2 class="ftco-heading-2">Have a Questions?</h2>
          <div class="block-23 mb-3">
            <ul>
              <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
              <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
              <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">

        <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
      </div>
    </div>
  </div>
</footer>

templates/head.html
{% load static %}
<title>Muscle - Free Bootstrap 4 Template by Colorlib</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed:100,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">

<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

<link rel="stylesheet" href="{% static 'css/aos.css' %}">

<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
<link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}">


<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/login.html
{% extends 'base.html' %}

{% block content %}
<br> <br> <br>
<form method="POST" action="">
  {% csrf_token %}
  <input type="text" name="username" placeholder="Username" class="form-control">
  <input type="password" name="password" placeholder="Password" class="form-control">

  <button type="submit">Log in</button>
</form>

{% endblock content %}

templates/member.html
{% extends 'base.html' %}

{% block content %}
<br> <br> <br>
<div class="container">
Hello {{ member.user }}
<br> <br>
{% if request.user.member.profile_pic %}
<img src="{{ request.user.member.profile_pic.url}}" width="100px" alt=""> <br> <br>
{% endif %}
<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}
{{ form }}
  <button type="submit">Submit</button>
</form> <br> <br>

Total workouts: {{ total_workouts }} <br>
Workouts in progress: {{ in_progres }} <br>
Finished workouts: {{ finished }} <br> <br>
<a href="{% url 'workout_form' %}">Add workout</a>
<br>

{% for workout in workouts %}
<div class="row">
<a href="{% url 'update_workout' workout.id %}">Update workout</a>
{{ workout.date_of_working }} <br>
{{ workout.name }} <br>
{{ workout.status }} <br>

{% for exercise in workout.exercise.all %}
  {{ exercise }}
  {{ exercise.content|safe }}
{% endfor %}
</div>
{% endfor %}
</div>
{% endblock content %}

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
  <div class="container">
    <a class="navbar-brand py-2 px-4" href="{% url 'index' %}">Muscle</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="oi oi-menu"></span> Menu
    </button>
    <div class="collapse navbar-collapse" id="ftco-nav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active"><a href="{% url 'index' %}" class="nav-link">Home</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"><a href="{% url 'member' %}" class="nav-link">See profile</a></li>
        {% endif %}
        <li class="nav-item"><a href="{% url 'program' %}" class="nav-link">Program</a></li>
        <li class="nav-item"><a href="coaches.html" class="nav-link">Coaches</a></li>
        <li class="nav-item"><a href="{% url 'about' %}" class="nav-link">About</a></li>
        <li class="nav-item"><a href="{% url 'blog:all_blogs' %}" class="nav-link">Blog</a></li>
        <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Log out</a></li>
        {% else %}
        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Log in</a></li>
        <li class="nav-item"><a href="{% url 'register' %}" class="nav-link">Sign up</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/program.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="ftco-section">
  <div class="container-fluid">
    <div class="row justify-content-center mb-5 pb-3">
      <div class="col-md-7 heading-section ftco-animate text-center">
        <h3 class="subheading">Gym Classes</h3>
        <h2 class="mb-1">Workout Classes</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-lg-3">
        <div class="package-program ftco-animate">
          <a href="{% url 'bodybuilding' %}" class="img d-flex justify-content-center align-items-center" style="background-image: url({% static 'images/program-1.jpg' %});">
            <span>See Exercise</span>
          </a>
          <div class="text mt-3">
            <h3><a href="#">Body Building</a></h3>
            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="package-program ftco-animate">
          <a href="{% url 'aerobic' %}" class="img d-flex justify-content-center align-items-center" style="background-image: url({% static 'images/program-2.jpg' %});">
            <span>See exercise</span>
          </a>
          <div class="text mt-3">
            <h3><a href="#">Aerobic Classes</a></h3>
            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="package-program ftco-animate">
          <a href="#" class="img d-flex justify-content-center align-items-center" style="background-image: url({% static 'images/program-3.jpg' %});">
            <span>Learn More</span>
          </a>
          <div class="text mt-3">
            <h3><a href="#">Weight Lifting</a></h3>
            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-lg-3">
        <div class="package-program ftco-animate">
          <a href="#" class="img d-flex justify-content-center align-items-center" style="background-image: url({% static 'images/program-4.jpg' %});">
            <span>Learn More</span>
          </a>
          <div class="text mt-3">
            <h3><a href="#">Yoga Classes</a></h3>
            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row mt-4 justify-content-center ftco-animate">
      <div class="col-md-4 text-center">
        <a href="#" class="btn-custom py-4">View More Program <span class="ion-ios-arrow-down ml-2"></span></a>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/register.html
{% extends 'base.html' %}
{% block content %}
<br> <br> <br>
<form method="POST" action="">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Register</button>
</form>

{% endblock content %}

templates/scripts.html
{% load static %}

<!-- loader -->
<div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>